AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  show-ratings-scraper
Resources:
  ShowRatingsScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
        - S3WritePolicy:
            BucketName: show-ratings-scraper-output
    Metadata:
      SamResourceId: ShowRatingsScraperFunction
  Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      ScheduleExpression: rate(1 day)
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt ShowRatingsScraperFunction.Arn
        RoleArn: !GetAtt ScheduleToShowRatingsScraperFunctionRole.Arn
  ScheduleToShowRatingsScraperFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: !Sub scheduler.${AWS::URLSuffix}
          Action: sts:AssumeRole
          Condition:
            ArnLike:
              aws:SourceArn: !Sub
                - arn:${AWS::Partition}:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/*/${AWS::StackName}-${ResourceId}-*
                - ResourceId: Schedule
      Policies:
        - PolicyName: StartExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt ShowRatingsScraperFunction.Arn